#!/bin/sh
# Workaround needed
# because legendofsajjad loads its data from a path relative to
# the current working directory (FIXME)
HERE="$(dirname "$(readlink -f "${0}")")"
cd "${HERE}/usr/bin"
exec ./legendofsajjad "$@"
